### ISSUE TITLE
Command /name

### ISSUE THREAD

**Issue by Tommy-XL** [music-discussion/TownOfHost-TheOtherRoles#14]
A suggestion to make a limit of 10 or 15 words in the /name command, otherwise someone will use it and spam

![image](https://user-images.githubusercontent.com/104814436/188270274-70e98728-98bd-4767-89d6-a3d010168beb.png)

**Comment by Tommy-XL** [comment]
And also so that the /color command does not work if the player enters a number greater than 17

**Comment by SkullCreeper** [comment]
I can fully understand having a character limit for the /name command.
For the /color command, it allows up to 20 so Fortegreen can be accessed, though we are well aware that games refuse to start when someone is Fortegreen. I can understand why people would want Fortegreen to be inaccessible though since it has many bugs with certain interactions, such as shapeshifting. A way to **disable** these commands are planned though.

**Comment by Tommy-XL** [comment]
Hmm, the team is actually quite good, but I ask the players not to use colors greater than 17, otherwise the lobby will get bugged

**Comment by Tommy-XL** [comment]
And by the way, Host can't use the /name command, is that normal?

**Comment by SkullCreeper** [comment]
They wouldn't need to as the /rename command exists for the host so they can change their name to their normal name without "TOH" in their name (as its needed to be in your name to make a public TOH lobby). The /rename command is also instant and appears for everyone (though this might be because its the host's name changing).

As for the comment for asking players not to use Fortegreen, we do that as well and just ban them if they refuse (though we allow it after the game started as it has no issues then except for the interaction issues I mentioned earlier).

**Comment by Tommy-XL** [comment]
Ah, I didn’t know that there was a /rename command, thanks for the tip, and yes, Fortegreen can be safely used during the game, but I think that this can also cause an error, so I tell everyone not to use it at all

**Comment by music-discussion** [comment]
I swear I coded in a max character limit of 20. I'll look into the code.
